# Generated by Django 4.0.5 on 2022-09-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Item name to display')),
                ('description', models.TextField(verbose_name='Description of item to display')),
                ('price', models.IntegerField(verbose_name='Price of item for checkout')),
            ],
        ),
    ]
