version: "3"

volumes:
  db:
    driver: local
# TODO: Database config should be:
# - "postgres" - "-c" "-config-file=/etc/postgresql/postgresql.conf"
# With volume on Docker.

services:
  database:
    image: postgres:14-alpine
    hostname: django-stripe
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - .database.env
    networks:
      - django-stripe
    command:
      - "postgres"
      - "-c" # Max connection limit for database.
      - "max_connections=1000" # SHOW max_connections;
      - "-c" # Buffer size for database bufferization.
      - "shared_buffers=128MB" # SHOW shared_buffers;
  database-poller:
    image: edoburu/pgbouncer
    env_file:
      - .database.env
    depends_on:
      - database
    networks:
      - django-stripe
  server:
    hostname: django-stripe
    restart: always
    env_file:
      - .server.env
    volumes:
      - ./:/srv
    ports:
      - "${COMPOSE_EXPOSED_PORT}:80"
    depends_on:
      - database
      - database-poller
    links:
      - database
    networks:
      - django-stripe
    build: .

networks:
  django-stripe:
